name: elix-star-live
static_sites:
  - name: web
    environment_slug: node-js
    source_dir: /
    build_command: npm ci && npm run build
    output_dir: dist
    catchall_document: index.html
    routes:
      - path: /
    envs:
      - key: VITE_SUPABASE_URL
        scope: BUILD_TIME
        value: REPLACE_ME
      - key: VITE_SUPABASE_ANON_KEY
        scope: BUILD_TIME
        value: REPLACE_ME
      - key: VITE_GIFT_ASSET_BASE_URL
        scope: BUILD_TIME
        value: REPLACE_ME
      - key: VITE_STRIPE_PUBLISHABLE_KEY
        scope: BUILD_TIME
        value: REPLACE_ME
