
const giftUrl = (path: string) => {
  const cleanPath = path.startsWith('/') ? path.slice(1) : path;
  const encodedPath = cleanPath.split('/').map((segment) => encodeURIComponent(segment)).join('/');
  const baseUrl = import.meta.env.BASE_URL.endsWith('/') ? import.meta.env.BASE_URL : `${import.meta.env.BASE_URL}/`;
  return `${baseUrl}${encodedPath}`;
};

export type GiftType = 'universe' | 'big' | 'small';

export type GiftItem = {
  id: string;
  name: string;
  coins: number;
  giftType: GiftType;
  isActive: boolean;
  icon: string;
  video: string;
  preview: string;
};

export const GIFTS: GiftItem[] = [
  // --- Small Gifts (Static) ---
  {
    id: 's_rose',
    name: 'Red Rose',
    coins: 1,
    giftType: 'small',
    isActive: true,
    icon: 'https://cdn-icons-png.flaticon.com/512/740/740935.png',
    video: 'https://cdn-icons-png.flaticon.com/512/740/740935.png',
    preview: 'https://cdn-icons-png.flaticon.com/512/740/740935.png',
  },
  {
    id: 's_heart',
    name: 'Love Heart',
    coins: 5,
    giftType: 'small',
    isActive: true,
    icon: 'https://cdn-icons-png.flaticon.com/512/833/833472.png',
    video: 'https://cdn-icons-png.flaticon.com/512/833/833472.png',
    preview: 'https://cdn-icons-png.flaticon.com/512/833/833472.png',
  },
  {
    id: 's_coffee',
    name: 'Morning Coffee',
    coins: 15,
    giftType: 'small',
    isActive: true,
    icon: 'https://cdn-icons-png.flaticon.com/512/924/924514.png',
    video: 'https://cdn-icons-png.flaticon.com/512/924/924514.png',
    preview: 'https://cdn-icons-png.flaticon.com/512/924/924514.png',
  },
  {
    id: 's_diamond',
    name: 'Blue Diamond',
    coins: 300,
    giftType: 'small',
    isActive: true,
    icon: 'https://cdn-icons-png.flaticon.com/512/2663/2663114.png',
    video: 'https://cdn-icons-png.flaticon.com/512/2663/2663114.png',
    preview: 'https://cdn-icons-png.flaticon.com/512/2663/2663114.png',
  },
  {
    id: 's_crown',
    name: 'King Crown',
    coins: 1500,
    giftType: 'small',
    isActive: true,
    icon: 'https://cdn-icons-png.flaticon.com/512/691/691065.png',
    video: 'https://cdn-icons-png.flaticon.com/512/691/691065.png',
    preview: 'https://cdn-icons-png.flaticon.com/512/691/691065.png',
  },
  {
    id: 's_panda',
    name: 'Cute Panda',
    coins: 10,
    giftType: 'small',
    isActive: true,
    icon: 'https://cdn-icons-png.flaticon.com/512/3069/3069172.png',
    video: 'https://cdn-icons-png.flaticon.com/512/3069/3069172.png',
    preview: 'https://cdn-icons-png.flaticon.com/512/3069/3069172.png',
  },
  {
    id: 's_butterfly',
    name: 'Blue Butterfly',
    coins: 25,
    giftType: 'small',
    isActive: true,
    icon: 'https://cdn-icons-png.flaticon.com/512/2979/2979563.png',
    video: 'https://cdn-icons-png.flaticon.com/512/2979/2979563.png',
    preview: 'https://cdn-icons-png.flaticon.com/512/2979/2979563.png',
  },
  {
    id: 's_cat',
    name: 'Happy Cat',
    coins: 50,
    giftType: 'small',
    isActive: true,
    icon: 'https://cdn-icons-png.flaticon.com/512/616/616430.png',
    video: 'https://cdn-icons-png.flaticon.com/512/616/616430.png',
    preview: 'https://cdn-icons-png.flaticon.com/512/616/616430.png',
  },
  {
    id: 's_dog',
    name: 'Puppy Love',
    coins: 100,
    giftType: 'small',
    isActive: true,
    icon: 'https://cdn-icons-png.flaticon.com/512/194/194279.png',
    video: 'https://cdn-icons-png.flaticon.com/512/194/194279.png',
    preview: 'https://cdn-icons-png.flaticon.com/512/194/194279.png',
  },
  {
    id: 's_sun',
    name: 'Sunny Day',
    coins: 250,
    giftType: 'small',
    isActive: true,
    icon: 'https://cdn-icons-png.flaticon.com/512/869/869869.png',
    video: 'https://cdn-icons-png.flaticon.com/512/869/869869.png',
    preview: 'https://cdn-icons-png.flaticon.com/512/869/869869.png',
  },
  {
    id: 's_rainbow',
    name: 'Rainbow',
    coins: 500,
    giftType: 'small',
    isActive: true,
    icon: 'https://cdn-icons-png.flaticon.com/512/265/265674.png',
    video: 'https://cdn-icons-png.flaticon.com/512/265/265674.png',
    preview: 'https://cdn-icons-png.flaticon.com/512/265/265674.png',
  },
  {
    id: 's_unicorn',
    name: 'Mini Unicorn',
    coins: 1000,
    giftType: 'small',
    isActive: true,
    icon: 'https://cdn-icons-png.flaticon.com/512/3468/3468081.png',
    video: 'https://cdn-icons-png.flaticon.com/512/3468/3468081.png',
    preview: 'https://cdn-icons-png.flaticon.com/512/3468/3468081.png',
  },

  // --- Video Gifts (Auto-generated from public/gifts) ---
  {
    id: 'global_universe',
    name: 'Global Universe',
    coins: 1000000,
    giftType: 'universe',
    isActive: true,
    icon: giftUrl('/gifts/Elix Global Universe.png'),
    video: giftUrl('/gifts/Elix Global Universe.webm'),
    preview: giftUrl('/gifts/Elix Global Universe.png'),
  },
  {
    id: 'horse_gallop',
    name: 'Galloping Horse',
    coins: 5000,
    giftType: 'big',
    isActive: true,
    icon: giftUrl('/gifts/Horse.png'),
    video: giftUrl('/gifts/Horse.mp4'),
    preview: giftUrl('/gifts/Horse.png'),
  },
  {
    id: 'rex_dino',
    name: 'T-Rex',
    coins: 12000,
    giftType: 'big',
    isActive: true,
    icon: giftUrl('/gifts/Rex Dinosaur.png'),
    video: giftUrl('/gifts/Rex Dinosaur.mp4'),
    preview: giftUrl('/gifts/Rex Dinosaur.png'),
  },
  {
    id: 'treasure_chest',
    name: 'Treasure Chest',
    coins: 15000,
    giftType: 'big',
    isActive: true,
    icon: giftUrl('/gifts/A gleaming treasure chest in a cave.png'),
    video: giftUrl('/gifts/A gleaming treasure chest in a cave.mp4'),
    preview: giftUrl('/gifts/A gleaming treasure chest in a cave.png'),
  },
  {
    id: 'war_bird',
    name: 'War Bird',
    coins: 15000,
    giftType: 'big',
    isActive: true,
    icon: giftUrl('/gifts/Fantasy celestial war-bird.png'),
    video: giftUrl('/gifts/Fantasy celestial war-bird.mp4'),
    preview: giftUrl('/gifts/Fantasy celestial war-bird.png'),
  },
  {
    id: 'kitty_treasure',
    name: 'Kitty Treasure',
    coins: 17000,
    giftType: 'big',
    isActive: true,
    icon: giftUrl('/gifts/Crown Kitty Treasure.png'),
    video: giftUrl('/gifts/Crown Kitty Treasure.mp4'),
    preview: giftUrl('/gifts/Crown Kitty Treasure.png'),
  },
  {
    id: 'frost_wolf',
    name: 'Frost Wolf',
    coins: 18000,
    giftType: 'big',
    isActive: true,
    icon: giftUrl('/gifts/Frost Wolf.png'),
    video: giftUrl('/gifts/Frost Wolf.mp4'),
    preview: giftUrl('/gifts/Frost Wolf.png'),
  },
  {
    id: 'voyager_ship',
    name: 'Voyager Ship',
    coins: 19000,
    giftType: 'big',
    isActive: true,
    icon: giftUrl('/gifts/Crystal Voyager Ship.png'),
    video: giftUrl('/gifts/Crystal Voyager Ship.mp4'),
    preview: giftUrl('/gifts/Crystal Voyager Ship.png'),
  },
  {
    id: 'fiery_lion',
    name: 'Fiery Lion',
    coins: 21000,
    giftType: 'big',
    isActive: true,
    icon: giftUrl('/gifts/Fiery lion in blazing glory.png'),
    video: giftUrl('/gifts/Fiery lion in blazing glory.mp4'),
    preview: giftUrl('/gifts/Fiery lion in blazing glory.png'),
  },
  {
    id: 'night_panther',
    name: 'Night Panther',
    coins: 22000,
    giftType: 'big',
    isActive: true,
    icon: giftUrl('/gifts/Night Panther.png'),
    video: giftUrl('/gifts/Night Panther.mp4'),
    preview: giftUrl('/gifts/Night Panther.png'),
  },
  {
    id: 'titan_gorilla',
    name: 'Titan Gorilla',
    coins: 23000,
    giftType: 'big',
    isActive: true,
    icon: giftUrl('/gifts/Earth Titan Gorilla.png'),
    video: giftUrl('/gifts/Earth Titan Gorilla.mp4'),
    preview: giftUrl('/gifts/Earth Titan Gorilla.png'),
  },
  {
    id: 'misty_wolf',
    name: 'Misty Wolf',
    coins: 25000,
    giftType: 'big',
    isActive: true,
    icon: giftUrl('/gifts/Ferocious wolf in misty terrain.png'),
    video: giftUrl('/gifts/Ferocious wolf in misty terrain.mp4'),
    preview: giftUrl('/gifts/Ferocious wolf in misty terrain.png'),
  },
  {
    id: 'cosmic_panther',
    name: 'Cosmic Panther',
    coins: 26000,
    giftType: 'big',
    isActive: true,
    icon: giftUrl('/gifts/Cosmic Panther.png'),
    video: giftUrl('/gifts/Cosmic Panther.mp4'),
    preview: giftUrl('/gifts/Cosmic Panther.png'),
  },
  {
    id: 'star_wand',
    name: 'Star Wand',
    coins: 28000,
    giftType: 'big',
    isActive: true,
    icon: giftUrl('/gifts/Celestial Star Wand.png'),
    video: giftUrl('/gifts/Celestial Star Wand.mp4'),
    preview: giftUrl('/gifts/Celestial Star Wand.png'),
  },
  {
    id: 'beast_relic',
    name: 'Beast Relic',
    coins: 31000,
    giftType: 'big',
    isActive: true,
    icon: giftUrl('/gifts/Beast Relic of the Ancients.png'),
    video: giftUrl('/gifts/Beast Relic of the Ancients.webm'),
    preview: giftUrl('/gifts/Beast Relic of the Ancients.png'),
  },
  {
    id: 'crystal_rhino',
    name: 'Crystal Rhino',
    coins: 32000,
    giftType: 'big',
    isActive: true,
    icon: giftUrl('/gifts/Crystal Rhino.png'),
    video: giftUrl('/gifts/Crystal Rhino.mp4'),
    preview: giftUrl('/gifts/Crystal Rhino.png'),
  },
  {
    id: 'storm_phoenix',
    name: 'Storm Phoenix',
    coins: 34000,
    giftType: 'big',
    isActive: true,
    icon: giftUrl('/gifts/Arcane Storm Phoenix.png'),
    video: giftUrl('/gifts/Arcane Storm Phoenix.mp4'),
    preview: giftUrl('/gifts/Arcane Storm Phoenix.png'),
  },
  {
    id: 'ice_sorceress',
    name: 'Ice Sorceress',
    coins: 37000,
    giftType: 'big',
    isActive: true,
    icon: giftUrl('/gifts/Elix Ice Sorceress.png'),
    video: giftUrl('/gifts/Elix Ice Sorceress.mp4'),
    preview: giftUrl('/gifts/Elix Ice Sorceress.png'),
  },
  {
    id: 'fire_phoenix',
    name: 'Fire Phoenix',
    coins: 38000,
    giftType: 'big',
    isActive: true,
    icon: giftUrl('/gifts/Fire Phoenix.png'),
    video: giftUrl('/gifts/Fire Phoenix.mp4'),
    preview: giftUrl('/gifts/Fire Phoenix.png'),
  },
  {
    id: 'lavarok',
    name: 'Lavarok',
    coins: 40000,
    giftType: 'big',
    isActive: true,
    icon: giftUrl('/gifts/Lavarok.png'),
    video: giftUrl('/gifts/Lavarok.mp4'),
    preview: giftUrl('/gifts/Lavarok.png'),
  },
  {
    id: 'blazing_wizard',
    name: 'Blazing Wizard',
    coins: 42000,
    giftType: 'big',
    isActive: true,
    icon: giftUrl('/gifts/Fiery power of the blazing wizard.png'),
    video: giftUrl('/gifts/Fiery power of the blazing wizard.mp4'),
    preview: giftUrl('/gifts/Fiery power of the blazing wizard.png'),
  },
  {
    id: 'aelyra_flameveil',
    name: 'Aelyra Flameveil',
    coins: 45000,
    giftType: 'big',
    isActive: true,
    icon: giftUrl('/gifts/Aelyra Flameveil.png'),
    video: giftUrl('/gifts/Aelyra Flameveil.mp4'),
    preview: giftUrl('/gifts/Aelyra Flameveil.png'),
  },
  {
    id: 'golden_lion',
    name: 'Golden Lion',
    coins: 46000,
    giftType: 'big',
    isActive: true,
    icon: giftUrl('/gifts/Golden Rage Lion.png'),
    video: giftUrl('/gifts/Golden Rage Lion.mp4'),
    preview: giftUrl('/gifts/Golden Rage Lion.png'),
  },
  {
    id: 'dragon_egg',
    name: 'Dragon Egg',
    coins: 49000,
    giftType: 'big',
    isActive: true,
    icon: giftUrl('/gifts/Ember Dragon Egg.png'),
    video: giftUrl('/gifts/Ember Dragon Egg.mp4'),
    preview: giftUrl('/gifts/Ember Dragon Egg.png'),
  },
  {
    id: 'lava_demon',
    name: 'Lava Demon',
    coins: 52000,
    giftType: 'big',
    isActive: true,
    icon: giftUrl('/gifts/Lava Demon.png'),
    video: giftUrl('/gifts/Lava Demon.mp4'),
    preview: giftUrl('/gifts/Lava Demon.png'),
  },
  {
    id: 'dragon_wrath',
    name: 'Dragon Wrath',
    coins: 55000,
    giftType: 'big',
    isActive: true,
    icon: giftUrl('/gifts/Dragon’s Wrath Ride.png'),
    video: giftUrl('/gifts/Dragon’s Wrath Ride.mp4'),
    preview: giftUrl('/gifts/Dragon’s Wrath Ride.png'),
  },
  {
    id: 'flames_royalty',
    name: 'Flames Royalty',
    coins: 55000,
    giftType: 'big',
    isActive: true,
    icon: giftUrl('/gifts/Flames and royalty on fiery ground.png'),
    video: giftUrl('/gifts/Flames and royalty on fiery ground.mp4'),
    preview: giftUrl('/gifts/Flames and royalty on fiery ground.png'),
  },
  {
    id: 'fire_unicorn',
    name: 'Fire Unicorn',
    coins: 55000,
    giftType: 'big',
    isActive: true,
    icon: giftUrl('/gifts/Mythic Fire Unicorn.png'),
    video: giftUrl('/gifts/Mythic Fire Unicorn.mp4'),
    preview: giftUrl('/gifts/Mythic Fire Unicorn.png'),
  },
  {
    id: 'thunder_falcon',
    name: 'Thunder Falcon',
    coins: 58000,
    giftType: 'big',
    isActive: true,
    icon: giftUrl('/gifts/Elix Thunder Falcon.png'),
    video: giftUrl('/gifts/Elix Thunder Falcon.mp4'),
    preview: giftUrl('/gifts/Elix Thunder Falcon.png'),
  },
  {
    id: 'infernal_lion',
    name: 'Infernal Lion',
    coins: 60000,
    giftType: 'big',
    isActive: true,
    icon: giftUrl('/gifts/Infernal Lion King.png'),
    video: giftUrl('/gifts/Infernal Lion King.mp4'),
    preview: giftUrl('/gifts/Infernal Lion King.png'),
  },
  {
    id: 'fantasy_unicorn',
    name: 'Fantasy Unicorn',
    coins: 61000,
    giftType: 'big',
    isActive: true,
    icon: giftUrl('/gifts/Fantasy Unicorn.png'),
    video: giftUrl('/gifts/Fantasy Unicorn.mp4'),
    preview: giftUrl('/gifts/Fantasy Unicorn.png'),
  },
  {
    id: 'sky_guardian',
    name: 'Sky Guardian',
    coins: 64000,
    giftType: 'big',
    isActive: true,
    icon: giftUrl('/gifts/Eternal Guardian.png'),
    video: giftUrl('/gifts/Eternal Guardian.mp4'),
    preview: giftUrl('/gifts/Eternal Guardian.png'),
  },
  {
    id: 'majestic_bird',
    name: 'Majestic Bird',
    coins: 65000,
    giftType: 'big',
    isActive: true,
    icon: giftUrl('/gifts/Majestic Ice Blue Mythic Bird.png'),
    video: giftUrl('/gifts/Majestic Ice Blue Mythic Bird.mp4'),
    preview: giftUrl('/gifts/Majestic Ice Blue Mythic Bird.png'),
  },
  {
    id: 'flame_king',
    name: 'The Flame King',
    coins: 65000,
    giftType: 'big',
    isActive: true,
    icon: giftUrl('/gifts/The Flame King.png'),
    video: giftUrl('/gifts/The Flame King.mp4'),
    preview: giftUrl('/gifts/The Flame King.png'),
  },
  {
    id: 'majestic_phoenix',
    name: 'Majestic Phoenix',
    coins: 70000,
    giftType: 'big',
    isActive: true,
    icon: giftUrl('/gifts/Majestic phoenix soaring in flames.png'),
    video: giftUrl('/gifts/Majestic phoenix soaring in flames.mp4'),
    preview: giftUrl('/gifts/Majestic phoenix soaring in flames.png'),
  },
  {
    id: 'molten_fury',
    name: 'Molten Fury',
    coins: 75000,
    giftType: 'big',
    isActive: true,
    icon: giftUrl('/gifts/Molten fury of the lava dragon.png'),
    video: giftUrl('/gifts/Molten fury of the lava dragon.mp4'),
    preview: giftUrl('/gifts/Molten fury of the lava dragon.png'),
  },
  {
    id: 'universe',
    name: 'Universe',
    coins: 80000,
    giftType: 'big',
    isActive: true,
    icon: giftUrl('/gifts/Elix Live Universe.png'),
    video: giftUrl('/gifts/Elix Live Universe.webm'),
    preview: giftUrl('/gifts/Elix Live Universe.png'),
  },
  {
    id: 'lava_rampage',
    name: 'Lava Rampage',
    coins: 80000,
    giftType: 'big',
    isActive: true,
    icon: giftUrl('/gifts/Rampage of the Lava Beast.png'),
    video: giftUrl('/gifts/Rampage of the Lava Beast.mp4'),
    preview: giftUrl('/gifts/Rampage of the Lava Beast.png'),
  },
  {
    id: 'guardian_chest',
    name: 'Guardian Chest',
    coins: 85000,
    giftType: 'big',
    isActive: true,
    icon: giftUrl('/gifts/Legendary guardians of treasure chest .png'),
    video: giftUrl('/gifts/Legendary guardians of treasure chest .mp4'),
    preview: giftUrl('/gifts/Legendary guardians of treasure chest .png'),
  },
  {
    id: 'storm_warrior',
    name: 'Storm Warrior',
    coins: 85000,
    giftType: 'big',
    isActive: true,
    icon: giftUrl('/gifts/Storm Warrior in Electric Fury.png'),
    video: giftUrl('/gifts/Storm Warrior in Electric Fury.mp4'),
    preview: giftUrl('/gifts/Storm Warrior in Electric Fury.png'),
  },
  {
    id: 'pink_jet',
    name: 'Pink Love Jet',
    coins: 88000,
    giftType: 'big',
    isActive: true,
    icon: giftUrl('/gifts/Pink Love Jet.png'),
    video: giftUrl('/gifts/Pink Love Jet.mp4'),
    preview: giftUrl('/gifts/Pink Love Jet.png'),
  },
  {
    id: 'frost_lion',
    name: 'Frost Lion',
    coins: 90000,
    giftType: 'big',
    isActive: true,
    icon: giftUrl('/gifts/Froststorm Lion.png'),
    video: giftUrl('/gifts/Froststorm Lion.mp4'),
    preview: giftUrl('/gifts/Froststorm Lion.png'),
  },
  {
    id: 'night_owl',
    name: 'Night Owl',
    coins: 90000,
    giftType: 'big',
    isActive: true,
    icon: giftUrl('/gifts/Stormborn Night Owl.png'),
    video: giftUrl('/gifts/Stormborn Night Owl.mp4'),
    preview: giftUrl('/gifts/Stormborn Night Owl.png'),
  },
  {
    id: 'drake_cub',
    name: 'Drake Cub',
    coins: 95000,
    giftType: 'big',
    isActive: true,
    icon: giftUrl('/gifts/Treasure Drake Cub.png'),
    video: giftUrl('/gifts/Treasure Drake Cub.mp4'),
    preview: giftUrl('/gifts/Treasure Drake Cub.png'),
  },
  {
    id: 'romantic_jet',
    name: 'Romantic Jet',
    coins: 99000,
    giftType: 'big',
    isActive: true,
    icon: giftUrl('/gifts/Romantic Jet.png'),
    video: giftUrl('/gifts/Romantic Jet.mp4'),
    preview: giftUrl('/gifts/Romantic Jet.png'),
  },
  {
    id: 'guardian_vault',
    name: 'Guardian Vault',
    coins: 100000,
    giftType: 'big',
    isActive: true,
    icon: giftUrl('/gifts/Mythic Beast Vault (Phoenix, Lion, Dragon, Bear, Wolf).png'),
    video: giftUrl('/gifts/Mythic Beast Vault (Phoenix, Lion, Dragon, Bear, Wolf).mp4'),
    preview: giftUrl('/gifts/Mythic Beast Vault (Phoenix, Lion, Dragon, Bear, Wolf).png'),
  },
  {
    id: 'elix_gold_universe',
    name: 'Gold Universe',
    coins: 120000,
    giftType: 'big',
    isActive: true,
    icon: giftUrl('/gifts/Elix Gold Universe.png'),
    video: giftUrl('/gifts/Elix Gold Universe.webm'),
    preview: giftUrl('/gifts/Elix Gold Universe.png'),
  },
];
